language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
cache: cargo
script:
    - cargo build --verbose --all
    - sudo -E env cargo test --verbose --all
