language: rust

# TODO - also test *-musl targets
rust:
    - stable
    - beta
    - nightly

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

arch:
    - amd64
    - arm64

os:
    - linux
    - osx

matrix:
    allow_failures:
        - rust: nightly
