language: rust

# TODO - also test *-musl targets
# TODO - also do the fmt check

rust:
    - stable
    - beta
    - nightly

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

arch:
    - amd64
    - arm64

os:
  - linux
  - osx

script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ];  then 
          cargo build --verbose;
          cargo test --verbose --all-targets;
      else
          if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then 
            cargo build --workspace --verbose --all-features;
            cargo test --workspace --verbose --all-features;
          else
              cargo build --verbose;
              cargo test --verbose;
          fi
      fi

branches:
  only:
  - master

matrix:
    allow_failures:
        - os: osx
