[workspace]
members = [
    "bs-cbpf", 
    "bs-ebpf", 
    "bs-filter", 
    "bs-socket",
    "bs-system",
    "bs",
]
default-members = [
    "bs-cbpf", 
    "bs-filter", 
    "bs-socket",
    "bs-system",
    "bs",
]
