[package]
name = "bs-socket"
version = "0.1.0"
authors = ["Oskar Matzerath <moskar.drummer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bs-filter"]

[dependencies]
libc = "0.2"
bs-filter = { path = "../bs-filter", version = "0.1" , optional = true }
bs-sockopt = { path = "../bs-sockopt", version = "0.1" }
